version: '3'
services:
   mysql:  
    image: mysql:8
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=Oumayma 
      - MYSQL_DATABASE=releasemanagement 
      - MYSQL_USER=Oumayma
      - MYSQL_PASSWORD=Oumayma
          
   tomcat: 
     build: .
     ports: 
      - "8076:8076"
     environment:
      - MYSQL_ROOT_PASSWORD=Oumayma 
      - MYSQL_DATABASE=releasemanagement 
      - MYSQL_USER=Oumayma
      - MYSQL_PASSWORD=Oumayma
      - MYSQL_PORT=3306
      - SPRING_DATABASE_URL=jdbc:mysql//mysql:3306/releasemanagement
     links: 
      - mysql